articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns=[
    path('index/', views.index),
    path('dinner/', views.dinner, name='dinner'),
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

django_tutoral/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    # path('foods/', include('foods.urls')),
]

articles/models.py
from venv import create
from django.db import models

# Create your models here.
class Article(models.Model):  # models.Model: 상속
    # id(primary key)는 자동으로 만들어진다
    title = models.CharField(max_length=10)
    content = models.TextField()
    create_at = models.DateField(auto_now_add=True)  # 생성시에 자동으로 추가
    

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
from turtle import title
from django.shortcuts import render, redirect
import random

import articles
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'index.html')

def dinner(request):
    menus = [{'name': '족발', 'price': 30000}, {'name': '햄버거', 'price': 5000}, {'name': '치킨', 'price': 20000}, {'name': '초밥', 'price': 15000}]
    pick = random.choice(menus)
    articles = Article.objects.order_by('-pk') 
    context = {
        'pick': pick,
        'menus': menus,
        'articles': articles,
    }
    return render(request, 'dinner.html', context)

def review(request):
    return render(request, 'review.html')

def create_review(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()

    return redirect('articles:detail', article.pk)
 
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        article.delete()
    
    return redirect('articles:dinner')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'edit.html', context)

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오늘 뭐 먹지?</title>

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"></head>
<body class="container">
    {% block content %} 
    {% endblock %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/detail.html
{% extends 'base.html' %} {% block content %}
<h2 class="text-center">DETAIL</h2>
<h3>{{ article.pk }}번째 글</h3>
<hr />
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>작성 시간: {{ article.create_at|date:"SHORT_DATE_FORMAT"}}</p>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
</form>
<a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">EDIT</a><br />
<a href="{% url 'articles:dinner' %}">[back]</a>
<hr />
{% endblock %}

articles/templates/dinner.html
{% extends 'base.html' %} 
{% block content %}

<h1>오늘 저녁은 {{ pick.name }}입니다</h1>
<h1>메뉴 리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{ menu.name }} {{ menu.price }}원</li>
    {% endfor %}
</ul>

{% if pick.price > 20000 %}
<p>비싸다!</p>
{% elif pick.price > 10000 %}
<p>해볼만하다!</p>
{% else %}
<p>맛있겠다!</p>
{% endif %} 

<h1>리뷰 리스트</h1>
{% for article in articles %}
<a href="{% url 'articles:review' %}">[리뷰 작성하기]</a>
<p>글 번호: {{ article.pk }}</p>
<p>글 제목: {{ article.title }}</p>
<p>글 내용: {{ article.content }}</p>
<a href="{% url 'articles:detail' article.pk %}">[detail]</a>
<hr />
{% endfor %} {% endblock %}

articles/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">EDIT</h1>
<form class="form-group" action="#" method="POST">
{% csrf token %}
    <label for="title">Title: </label>
    <input class="form-control" type="text" name="'title" value="{{ article.title }}" /><br>
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <input type="submit" />
</form>


{% endblock %}

articles/templates/index.html
<h1>거북이반</h1>

articles/templates/review.html
{% extends 'base.html' %} {% block content %}

<form
    class="form-group"
    action="{% url 'articles:create_review' %}"
    method="POST"
>
    {% csrf_token %}
    <label for="title">Title: </label>
    <input class="form-control" type="text" name="title" /><br />
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5"></textarea><br />
    <input type="submit" />
</form>

{% endblock %}

articles/templates/review_result.html
<h1>보내서 받은 내용은 {{ content }}</h1>